### ISSUE TITLE
How can I load kafka extension to this?

### ISSUE THREAD

**Issue by visakhmurukes** [anskarl/druid-docker-cluster#1]
Trying to ingest some data from Kafka. But the option is disabled in console
Tried adding druid-kafka-indexing-service to druid-entrypoint.sh but still it doesnt work

Would really appreciate some assistance

**Comment by anskarl** [comment]
I think that you need to re-build the images (e.g., `docker-compose build`) in order to enable another extension. Anyway, I've just pushed an update for Druid version 0.16.1-incubating and I have also enabled `druid-kafka-indexing-service`.

**Comment by visakhmurukes** [comment]
Thanks 
This fixed earlier issue however the druid console gives this exception

![druiderror](https://user-images.githubusercontent.com/14180077/73131576-e699de80-4026-11ea-9ccb-d1a92fda00b8.png)


The log shows the below

_

> Metadata storage is up! \o/
> Zookeper is up! \o/
> Deep storage is up! \o/
> Jan 24, 2020 5:36:03 PM org.hibernate.validator.internal.util.Version <clinit>
> INFO: HV000001: Hibernate Validator 5.1.3.Final
> usage: druid <command> [<args>]
> 
> The most commonly used druid commands are:
>     help       Display help information
>     index      Run indexing for druid
>     internal   Processes that Druid runs "internally", you should rarely use these directly
>     server     Run one of the Druid server types.
>     tools      Various tools for working with Druid
>     version    Returns Druid version information

Also I found the druid build and buckets containers exiting almost immediately after it starts 
_

**Comment by anskarl** [comment]
@visakhmurukes if you wait couple of minutes to let Druid initialize all of its services you will have a working environment like below:

![Screenshot 2020-01-27 at 09 40 26](https://user-images.githubusercontent.com/7415349/73157299-3b059280-40e9-11ea-8aee-779440cf0a62.png)

Regarding `druid-docker-cluster_create_buckets_1` and `druid-docker-cluster_druid_build_1`, thay are utility containers that run once and thereafter exit. `druid-docker-cluster_druid_build_1` is for creating Druid docker images from docker-compose and `druid-docker-cluster_create_buckets_1` initializes the contents of [minio](https://min.io/) image (for S3 emulation) in order to have the required buckets with the correct permissions. Both utility images are needed only for the first time. 

Please note that in order to have an environment with Kafka, you may need to add Kafka service in the `docker-compose.yaml` and make sure to [link](https://docs.docker.com/compose/compose-file/#links) with Druid `middlemanager` service (maybe also with `overlord` service). If you are running Kafka from another `docker-compose` or `docker run`, I think that you will need an [external_link](https://docs.docker.com/compose/compose-file/#external_links) (I haven't tested yet).

**Comment by visakhmurukes** [comment]
Thanks @anskarl 
Sorry for not getting back since then. Was working on few priorities
I got it sorted
As you specified, I waited for a while and then all services came up
And yes Kafka is running from a different docker compose inside another server so I referred it via IP through Load Data option giving the broker port. I was able to pull Kafka topic data to Druid like this
Thanks for all the quick help and support provided.
You're really a life saver :)
